apiVersion: v1
kind: Service
metadata:
  labels:
    app: zk3
  name: zk3
spec:
  ports:
    - name: zk-client-port
      port: 2181
      protocol: TCP
      targetPort: 2181
    - name: zk-follwer-port
      port: 2888
      protocol: TCP
      targetPort: 2888
    - name: zk-election-port
      port: 3888
      protocol: TCP
      targetPort: 3888
    - name: zk-admin-server-port
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: zk3
  type: ClusterIP
